version: 2.1

orbs:
  android: circleci/android@0.2.1

jobs:
  build:
    executor: android/android
    steps:
      - checkout
      - restore_cache:
          key: android-orb-v1-{{ checksum "gradle.lockfile" }}
      - run:
          name: Chmod permissions
          command: sudo chmod +x ./gradlew
      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies --no-daemon
      - save_cache:
          key: 'android-orb-v1-{{ checksum "gradle.lockfile" }}'
          paths:
            - ~/.android/build-cache
            - ~/.android/cache
      - run:
          name: Run Build
          command: ./gradlew build --no-daemon --stacktrace
      - store_artifacts: 
          path: app/build/reports
          destination: reports
      - run:
          name: Run Lint
          command: ./gradlew lint --no-daemon
      - run:
          name: Run Unit Tests
          command: ./gradlew test --no-daemon
      - store_test_results:
          path: app/build/test-results
      - store_artifacts:  
          path: app/build/outputs/apk/debug/
          destination: artifact-file
